### ISSUE TITLE
inline js code is script tags is not processed correctly

### ISSUE THREAD

**Issue by vehsakul** [aruntk/polymer-webpack-demo#3]
Hi!
From the comment 

> // es6 works here
const exampleItem = {
  is: 'example-item',
  foo(){}
}

and judging by your code it seems that js code in script tags should be forwarded to babel before inserted. This does not seem to work correctly. Scripts with src are ok.

Could you check if you have the same behavior?

**Comment by aruntk** [comment]
@vehsakul Fixed the issue. https://github.com/aruntk/wc-loader/blob/master/src/index.js#L166-L168
